# Generated by Django 5.0.3 on 2024-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_booking", "0003_alter_ticket_performance_alter_ticket_row_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "performance"),
                name="unique_ticket_for_performance",
            ),
        ),
    ]
